apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: tax-calculator-pipeline
spec:
  workspaces:
    - name: shared-workspace
  tasks:
    - name: npminstall
      taskRef:
        name: npm-install
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: tests
      taskRef:
        name: jasmine-test
      runAfter:
        - npminstall
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: build
      taskRef:
        name: buildah
        kind: ClusterTask
      runAfter:
        - tests
      workspaces:
        - name: source
          workspace: shared-workspace
